# Generated by Django 4.2.25 on 2026-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0060_merge_20251212_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="enable_model_card_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="leaderboard_use_model_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="model_card_is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="model_card_template_json",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="model_card_json",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="model_card_schema_version",
            field=models.CharField(blank=True, default="v1", max_length=50),
        ),
        migrations.AddField(
            model_name="submission",
            name="model_card_valid",
            field=models.BooleanField(default=False),
        ),
    ]
