# Generated by Django 4.2.25 on 2026-03-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0061_competition_enable_model_card_submission_and_more"),
        ("competitions", "0063_competition_rolling_period_bounds"),
    ]

    operations = []
