# Generated by Django 4.2.25 on 2026-03-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0064_merge_20260304_0751"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="model_card_json",
            new_name="model_card_parsed_json",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="model_card_schema_version",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="model_card_valid",
        ),
        migrations.AddField(
            model_name="submission",
            name="model_card_file",
            field=models.FileField(
                blank=True, null=True, upload_to="submission_model_cards/"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="model_card_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploaded", "Uploaded"),
                    ("parsed", "Parsed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="model_card_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
